
package antifriendzone;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres_SrPio
 */
public class AntiFriendZone extends javax.swing.JFrame {

    /**
     * Creates new form AntiFriendZone
     */
    public AntiFriendZone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        BtnSi = new javax.swing.JButton();
        BtnNo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setText("¿Quieres ser mi novia?");

        BtnSi.setText("Sí");
        BtnSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSi.setFocusPainted(false);
        BtnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiActionPerformed(evt);
            }
        });

        BtnNo.setText("No");
        BtnNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNo.setFocusPainted(false);
        BtnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnNoMouseEntered(evt);
            }
        });

        jLabel1.setText("By: Sr_Pio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(BtnNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSi)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Titulo)
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNo)
                    .addComponent(BtnSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNoMouseEntered

        Random r = new Random();
        int low = 1;
        int high = 328;  //El boton mide 72 de largo, entonces para que no se salga de la pantalla
        int result1 = r.nextInt(high - low) + low;

        int low2 = 1;
        int high2 = 250;
        int result2 = r.nextInt(high2 - low2) + low2;

        BtnNo.setLocation(result1, result2);
    }//GEN-LAST:event_BtnNoMouseEntered

    private void BtnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiActionPerformed

        JOptionPane.showMessageDialog(null, "Sabía que dirías que sí   :3");
    }//GEN-LAST:event_BtnSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        AntiFriendZone ventana = new AntiFriendZone();
        ventana.setBounds(0, 0, 400, 300);
        ventana.setVisible(true);
        ventana.setResizable(false);
        ventana.setLocationRelativeTo(null);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new AntiFriendZone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNo;
    private javax.swing.JButton BtnSi;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
